name: ðŸ–ï¸ Tag Version & Push

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tag-release:
    runs-on: MACOS-ARM64

    steps:
      - name: ðŸ“œ Get Codebase
        id: get_codebase
        uses: actions/checkout@v4

      - name: ðŸ“¨ Get Version from `pom.xml`
        run: |
          POM_VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml) || exit 1
          if [ -z "$POM_VERSION" ]; then
            echo "Version extraction failed"
            exit 1
          fi
          echo "VERSION=$POM_VERSION" >> $GITHUB_ENV

      - name: ðŸ§ Validate Version Format
        run: |
          if ! [[ "${{ env.VERSION }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format: ${{ env.VERSION }}"
            exit 1
          fi

      - name: ðŸ“ Create Tag and Push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag v${{ env.VERSION }} || { echo "Tagging failed"; exit 1; }
          git push origin v${{ env.VERSION }} || { echo "Pushing tag failed"; exit 1; }
          echo "COMPLETE: Tagged with v${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY

      - name: ðŸ§¹ Cleanup on Failure
        if: ${{ failure() }}
        run: |
          # Delete the local tag
          git tag -d v${{ env.VERSION }}
          echo "Deleted local tag due to failure."
          
          # Push the deletion to the remote repository
          git push --delete origin v${{ env.VERSION }}
          echo "Deleted remote tag due to failure."
